use `europeansoccerdatabase`;
CREATE TABLE `Country` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) UNIQUE
);


CREATE TABLE `League` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `country_id` INT,
    `name` VARCHAR(255) UNIQUE,
    FOREIGN KEY (`country_id`) REFERENCES `Country`(`id`)
);






CREATE TABLE `Player` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `player_api_id` INT UNIQUE,
    `player_name` VARCHAR(255),
    `player_fifa_api_id` INT UNIQUE,
    `birthday` VARCHAR(255),
    `height` INT,
    `weight` INT
);


CREATE TABLE `Player_Attributes` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `player_fifa_api_id` INT,
    `player_api_id` INT,
    `date` VARCHAR(255),
    `overall_rating` INT,
    `potential` INT,
    `preferred_foot` VARCHAR(255),
    `attacking_work_rate` VARCHAR(255),
    `defensive_work_rate` VARCHAR(255),
    `crossing` INT,
    `finishing` INT,
    `heading_accuracy` INT,
    `short_passing` INT,
    `volleys` INT,
    `dribbling` INT,
    `curve` INT,
    `free_kick_accuracy` INT,
    `long_passing` INT,
    `ball_control` INT,
    `acceleration` INT,
    `sprint_speed` INT,
    `agility` INT,
    `reactions` INT,
    `balance` INT,
    `shot_power` INT,
    `jumping` INT,
    `stamina` INT,
    `strength` INT,
    `long_shots` INT,
    `aggression` INT,
    `interceptions` INT,
    `positioning` INT,
    `vision` INT,
    `penalties` INT,
    `marking` INT,
    `standing_tackle` INT,
    `sliding_tackle` INT,
    `gk_diving` INT,
    `gk_handling` INT,
    `gk_kicking` INT,
    `gk_positioning` INT,
    `gk_reflexes` INT,
    FOREIGN KEY (`player_fifa_api_id`) REFERENCES `Player`(`player_fifa_api_id`),
    FOREIGN KEY (`player_api_id`) REFERENCES `Player`(`player_api_id`)
);




CREATE TABLE `Team` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `team_api_id` INT UNIQUE,
    `team_fifa_api_id` INT,
    `team_long_name` VARCHAR(255),
    `team_short_name` VARCHAR(255)
);

ALTER TABLE `Team`
ADD INDEX (`team_fifa_api_id`),
ADD INDEX (`team_api_id`);


CREATE TABLE `Team_Attributes` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `team_fifa_api_id` INT,
    `team_api_id` INT,
    `date` VARCHAR(255),
    `buildUpPlaySpeed` INT,
    `buildUpPlaySpeedClass` VARCHAR(255),
    `buildUpPlayDribbling` INT,
    `buildUpPlayDribblingClass` VARCHAR(255),
    `buildUpPlayPassing` INT,
    `buildUpPlayPassingClass` VARCHAR(255),
    `buildUpPlayPositioningClass` VARCHAR(255),
    `chanceCreationPassing` INT,
    `chanceCreationPassingClass` VARCHAR(255),
    `chanceCreationCrossing` INT,
    `chanceCreationCrossingClass` VARCHAR(255),
    `chanceCreationShooting` INT,
    `chanceCreationShootingClass` VARCHAR(255),
    `chanceCreationPositioningClass` VARCHAR(255),
    `defencePressure` INT,
    `defencePressureClass` VARCHAR(255),
    `defenceAggression` INT,
    `defenceAggressionClass` VARCHAR(255),
    `defenceTeamWidth` INT,
    `defenceTeamWidthClass` VARCHAR(255),
    `defenceDefenderLineClass` VARCHAR(255),
    FOREIGN KEY (`team_fifa_api_id`) REFERENCES `Team`(`team_fifa_api_id`),
    FOREIGN KEY (`team_api_id`) REFERENCES `Team`(`team_api_id`)
);



CREATE TABLE `Match` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `country_id` INT,
    `league_id` INT,
    `season` VARCHAR(255),
    `stage` INT,
    `date` VARCHAR(255),
    `match_api_id` INT UNIQUE,
    `home_team_api_id` INT,
    `away_team_api_id` INT,
    `home_team_goal` INT,
    `away_team_goal` INT,
    `home_player_X1` INT,
    `home_player_X2` INT,
    `home_player_X3` INT,
    `home_player_X4` INT,
    `home_player_X5` INT,
    `home_player_X6` INT,
    `home_player_X7` INT,
    `home_player_X8` INT,
    `home_player_X9` INT,
    `home_player_X10` INT,
    `home_player_X11` INT,
    `away_player_X1` INT,
    `away_player_X2` INT,
    `away_player_X3` INT,
    `away_player_X4` INT,
    `away_player_X5` INT,
    `away_player_X6` INT,
    `away_player_X7` INT,
    `away_player_X8` INT,
    `away_player_X9` INT,
    `away_player_X10` INT,
    `away_player_X11` INT,
    `home_player_Y1` INT,
    `home_player_Y2` INT,
    `home_player_Y3` INT,
    `home_player_Y4` INT,
    `home_player_Y5` INT,
    `home_player_Y6` INT,
    `home_player_Y7` INT,
    `home_player_Y8` INT,
    `home_player_Y9` INT,
    `home_player_Y10` INT,
    `home_player_Y11` INT,
    `away_player_Y1` INT,
    `away_player_Y2` INT,
    `away_player_Y3` INT,
    `away_player_Y4` INT,
    `away_player_Y5` INT,
    `away_player_Y6` INT,
    `away_player_Y7` INT,
    `away_player_Y8` INT,
    `away_player_Y9` INT,
    `away_player_Y10` INT,
    `away_player_Y11` INT,
    `home_player_1` INT,
    `home_player_2` INT,
    `home_player_3` INT,
    `home_player_4` INT,
    `home_player_5` INT,
    `home_player_6` INT,
    `home_player_7` INT,
    `home_player_8` INT,
    `home_player_9` INT,
    `home_player_10` INT,
    `home_player_11` INT,
    `away_player_1` INT,
    `away_player_2` INT,
    `away_player_3` INT,
    `away_player_4` INT,
    `away_player_5` INT,
    `away_player_6` INT,
    `away_player_7` INT,
    `away_player_8` INT,
    `away_player_9` INT,
    `away_player_10` INT,
    `away_player_11` INT,
    `goal` TEXT,
    `shoton` TEXT,
    `shotoff` TEXT,
    `foulcommit` TEXT,
    `card` TEXT,
    `cross` TEXT,
    `corner` TEXT,
    `possession` TEXT,
    `B365H` DECIMAL(10, 2),
    `B365D` DECIMAL(10, 2),
    `B365A` DECIMAL(10, 2),
    `BWH` DECIMAL(10, 2),
    `BWD` DECIMAL(10, 2),
    `BWA` DECIMAL(10, 2),
    `IWH` DECIMAL(10, 2),
    `IWD` DECIMAL(10, 2),
    `IWA` DECIMAL(10, 2),
    `LBH` DECIMAL(10, 2),
    `LBD` DECIMAL(10, 2),
    `LBA` DECIMAL(10, 2),
    `PSH` DECIMAL(10, 2),
    `PSD` DECIMAL(10, 2),
    `PSA` DECIMAL(10, 2),
    `WHH` DECIMAL(10, 2),
    `WHD` DECIMAL(10, 2),
    `WHA` DECIMAL(10, 2),
    `SJH` DECIMAL(10, 2),
    `SJD` DECIMAL(10, 2),
    `SJA` DECIMAL(10, 2),
    `VCH` DECIMAL(10, 2),
    `VCD` DECIMAL(10, 2),
    `VCA` DECIMAL(10, 2),
    `GBH` DECIMAL(10, 2),
    `GBD` DECIMAL(10, 2),
    `GBA` DECIMAL(10, 2),
    `BSH` DECIMAL(10, 2),
    `BSD` DECIMAL(10, 2),
    `BSA` DECIMAL(10, 2),
    FOREIGN KEY (`country_id`) REFERENCES `Country`(`id`),
    FOREIGN KEY (`league_id`) REFERENCES `League`(`id`),
    FOREIGN KEY (`home_team_api_id`) REFERENCES `Team`(`team_api_id`),
    FOREIGN KEY (`away_team_api_id`) REFERENCES `Team`(`team_api_id`),
    FOREIGN KEY (`home_player_1`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_2`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_3`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_4`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_5`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_6`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_7`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_8`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_9`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_10`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`home_player_11`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_1`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_2`) REFERENCES `Player`(`player_api_id`),
	FOREIGN KEY (`away_player_3`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_4`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_5`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_6`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_7`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_8`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_9`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_10`) REFERENCES `Player`(`player_api_id`),
    FOREIGN KEY (`away_player_11`) REFERENCES `Player`(`player_api_id`)
);



